-- Amplía los libros IVA sin borrar registros. Ejecutar una vez antes de usar la nueva versión.
USE economia_db;
SET @ddl_iva = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE iva_compras ADD COLUMN condicion_iva VARCHAR(30) NOT NULL DEFAULT ''''', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'iva_compras' AND column_name = 'condicion_iva');
PREPARE migracion_iva FROM @ddl_iva;
EXECUTE migracion_iva;
DEALLOCATE PREPARE migracion_iva;
SET @ddl_iva = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE iva_compras ADD COLUMN neto_no_gravado DECIMAL(14,2) NOT NULL DEFAULT 0', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'iva_compras' AND column_name = 'neto_no_gravado');
PREPARE migracion_iva FROM @ddl_iva;
EXECUTE migracion_iva;
DEALLOCATE PREPARE migracion_iva;
SET @ddl_iva = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE iva_compras ADD COLUMN exento DECIMAL(14,2) NOT NULL DEFAULT 0', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'iva_compras' AND column_name = 'exento');
PREPARE migracion_iva FROM @ddl_iva;
EXECUTE migracion_iva;
DEALLOCATE PREPARE migracion_iva;
SET @ddl_iva = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE iva_compras ADD COLUMN alicuota DECIMAL(5,2) NOT NULL DEFAULT 0', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'iva_compras' AND column_name = 'alicuota');
PREPARE migracion_iva FROM @ddl_iva;
EXECUTE migracion_iva;
DEALLOCATE PREPARE migracion_iva;
SET @ddl_iva = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE iva_compras ADD COLUMN punto_venta INT NOT NULL DEFAULT 0', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'iva_compras' AND column_name = 'punto_venta');
PREPARE migracion_iva FROM @ddl_iva;
EXECUTE migracion_iva;
DEALLOCATE PREPARE migracion_iva;
SET @ddl_iva = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE iva_compras ADD COLUMN dni VARCHAR(8) NOT NULL DEFAULT ''''', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'iva_compras' AND column_name = 'dni');
PREPARE migracion_iva FROM @ddl_iva;
EXECUTE migracion_iva;
DEALLOCATE PREPARE migracion_iva;
SET @ddl_iva = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE iva_compras ADD COLUMN otros_percepciones DECIMAL(11,2) NOT NULL DEFAULT 0', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'iva_compras' AND column_name = 'otros_percepciones');
PREPARE migracion_iva FROM @ddl_iva;
EXECUTE migracion_iva;
DEALLOCATE PREPARE migracion_iva;
SET @ddl_iva = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE iva_compras ADD COLUMN horas DECIMAL(11,2) NOT NULL DEFAULT 0', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'iva_compras' AND column_name = 'horas');
PREPARE migracion_iva FROM @ddl_iva;
EXECUTE migracion_iva;
DEALLOCATE PREPARE migracion_iva;
ALTER TABLE iva_compras MODIFY COLUMN tipo_comprobante VARCHAR(40) NOT NULL;
SET @ddl_iva = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE iva_ventas ADD COLUMN condicion_iva VARCHAR(30) NOT NULL DEFAULT ''''', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'iva_ventas' AND column_name = 'condicion_iva');
PREPARE migracion_iva FROM @ddl_iva;
EXECUTE migracion_iva;
DEALLOCATE PREPARE migracion_iva;
SET @ddl_iva = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE iva_ventas ADD COLUMN neto_no_gravado DECIMAL(14,2) NOT NULL DEFAULT 0', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'iva_ventas' AND column_name = 'neto_no_gravado');
PREPARE migracion_iva FROM @ddl_iva;
EXECUTE migracion_iva;
DEALLOCATE PREPARE migracion_iva;
SET @ddl_iva = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE iva_ventas ADD COLUMN exento DECIMAL(14,2) NOT NULL DEFAULT 0', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'iva_ventas' AND column_name = 'exento');
PREPARE migracion_iva FROM @ddl_iva;
EXECUTE migracion_iva;
DEALLOCATE PREPARE migracion_iva;
SET @ddl_iva = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE iva_ventas ADD COLUMN alicuota DECIMAL(5,2) NOT NULL DEFAULT 0', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'iva_ventas' AND column_name = 'alicuota');
PREPARE migracion_iva FROM @ddl_iva;
EXECUTE migracion_iva;
DEALLOCATE PREPARE migracion_iva;
SET @ddl_iva = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE iva_ventas ADD COLUMN punto_venta INT NOT NULL DEFAULT 0', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'iva_ventas' AND column_name = 'punto_venta');
PREPARE migracion_iva FROM @ddl_iva;
EXECUTE migracion_iva;
DEALLOCATE PREPARE migracion_iva;
SET @ddl_iva = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE iva_ventas ADD COLUMN dni VARCHAR(8) NOT NULL DEFAULT ''''', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'iva_ventas' AND column_name = 'dni');
PREPARE migracion_iva FROM @ddl_iva;
EXECUTE migracion_iva;
DEALLOCATE PREPARE migracion_iva;
SET @ddl_iva = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE iva_ventas ADD COLUMN otros_percepciones DECIMAL(11,2) NOT NULL DEFAULT 0', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'iva_ventas' AND column_name = 'otros_percepciones');
PREPARE migracion_iva FROM @ddl_iva;
EXECUTE migracion_iva;
DEALLOCATE PREPARE migracion_iva;
SET @ddl_iva = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE iva_ventas ADD COLUMN horas DECIMAL(11,2) NOT NULL DEFAULT 0', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'iva_ventas' AND column_name = 'horas');
PREPARE migracion_iva FROM @ddl_iva;
EXECUTE migracion_iva;
DEALLOCATE PREPARE migracion_iva;
ALTER TABLE iva_ventas MODIFY COLUMN tipo_comprobante VARCHAR(40) NOT NULL;
